# Generated by Django 5.2.1 on 2025-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('about_place', models.TextField()),
                ('tour_highlights', models.CharField(max_length=200)),
                ('include', models.CharField(max_length=200)),
                ('exclude', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('sub_images', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]   
