# Generated by Django 5.2.1 on 2025-05-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('trending', 'Trending Places'), ('adventure', 'Adventure Places'), ('honeymoon', 'Honeymoon Places'), ('beach', 'Beach Places'), ('historical', 'Historical Places')], default='trending', max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='main_image',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
