# Generated by Django 5.2.1 on 2025-05-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0002_place_place_type_alter_place_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='main_image',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='sub_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
