# Generated by Django 5.2.1 on 2025-05-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0003_alter_place_main_image_alter_place_sub_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tour_itinerary',
        ),
    ]
