# Generated by Django 5.2.1 on 2025-05-19 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0003_alter_place_main_image_alter_place_sub_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='sub_images',
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place_sub_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_images', to='placeApi.place')),
            ],
        ),
    ]
