# Generated by Django 5.2.1 on 2025-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0004_remove_place_sub_images_placeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='places/sub_images/'),
        ),
    ]
