# Generated by Django 5.2.1 on 2025-05-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0005_remove_placeimage_uploaded_at_alter_place_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='image',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='places/sub_images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
