# Generated by Django 5.2.1 on 2025-05-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0007_rename_sub_image_placeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='places/main_images/'),
        ),
    ]
