# Generated by Django 5.2.1 on 2025-05-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0008_alter_place_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='main_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='places/main_images/'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='places/sub_images/'),
        ),
    ]
