# Generated by Django 5.2.1 on 2025-05-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0009_alter_place_main_image_alter_placeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('trending', 'Trending Places'), ('adventure', 'Adventure Places'), ('honeymoon', 'Honeymoon Places'), ('beach', 'Beach Places'), ('historical', 'Historical Places'), ('place', 'place')], default='trending', max_length=50),
        ),
    ]
