# Generated by Django 5.2.1 on 2025-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0011_alter_place_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
