# Generated by Django 5.2.1 on 2025-05-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0013_alter_place_price_title_itineraryday_itineraryphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryphoto',
            name='itinerary_day',
        ),
        migrations.AddField(
            model_name='place',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='sub_iterative_discription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='sub_iterative_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ItinerativeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='places/itinerativeimages')),
                ('i_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerative_image', to='placeApi.place')),
            ],
        ),
        migrations.DeleteModel(
            name='ItineraryDay',
        ),
        migrations.DeleteModel(
            name='itineraryPhoto',
        ),
    ]
