# Generated by Django 5.2.1 on 2025-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0014_remove_itineraryphoto_itinerary_day_place_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='sub_discription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
