# Generated by Django 5.2.1 on 2025-05-29 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0015_place_sub_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='day',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sub_discription',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sub_iterative_discription',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sub_iterative_title',
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('sub_iterative_description', models.CharField(blank=True, default='', max_length=200)),
                ('sub_description', models.TextField(blank=True, default='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='placeApi.place')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='places/itinerary_photos/')),
                ('itinerary_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='placeApi.itineraryday')),
            ],
        ),
        migrations.DeleteModel(
            name='ItinerativeImage',
        ),
    ]
