# Generated by Django 5.2.1 on 2025-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0016_remove_place_day_remove_place_sub_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='package_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
