# Generated by Django 5.2.1 on 2025-05-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0018_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Place',
            new_name='place',
        ),
    ]
