# Generated by Django 5.2.1 on 2025-06-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0019_rename_place_booking_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='children_ages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
