# Generated by Django 5.2.1 on 2025-06-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0020_booking_children_ages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='children_ages',
        ),
    ]
