# Generated by Django 5.2.1 on 2025-06-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0024_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='service_description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='service_title',
        ),
    ]
