# Generated by Django 5.2.1 on 2025-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0025_rename_description_service_service_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
