# Generated by Django 5.2.1 on 2025-06-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0027_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
