# Generated by Django 5.2.1 on 2025-06-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0028_service_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
    ]
