# Generated by Django 5.2.1 on 2025-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0030_service_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('trending', 'Trending Places'), ('five_day', '5 Days Package'), ('ten_day', '10 Days Package'), ('fifteen_day', '15 Days Package'), ('twenty_day', '20 Days Package'), ('twentyfive_day', '25 Days Package')], default='trending', max_length=50),
        ),
    ]
