# Generated by Django 5.2.1 on 2025-07-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0031_alter_place_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20)),
                ('instagram_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('whatsapp_link', models.URLField()),
                ('video_title', models.CharField(max_length=255)),
                ('video_subtitle', models.CharField(max_length=255)),
                ('video_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
