# Generated by Django 5.2.1 on 2025-07-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0032_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='video_description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='video_subtitle',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='video_title',
        ),
    ]
