# Generated by Django 5.2.1 on 2025-07-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0033_remove_contact_video_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('trending', 'Trending Places'), ('five_day', '5 Days Package'), ('seven_days', '7 Days Package'), ('eight_days', '8 Days Package'), ('ten_days', '10 Days Package'), ('fourteen_days', '14 Days Pakage'), ('eighteen_dyas', '18 Days Pakage')], default='trending', max_length=50),
        ),
    ]
