# Generated by Django 5.2.5 on 2025-08-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0034_alter_place_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='subtitle',
            field=models.TextField(),
        ),
    ]
