# Generated by Django 5.2.5 on 2025-08-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0035_alter_place_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='exclude',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='include',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='tour_highlights',
            field=models.TextField(blank=True, default=''),
        ),
    ]
