# Generated by Django 5.2.5 on 2025-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0036_alter_place_exclude_alter_place_include_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, default=''),
        ),
    ]
