# Generated by Django 5.2.5 on 2025-08-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0037_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='package_title',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='price_title',
            field=models.CharField(blank=True, default=''),
        ),
    ]
