# Generated by Django 5.2.5 on 2025-08-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0038_alter_place_package_title_alter_place_price_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='front/company_logo/')),
                ('logo_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='front/logo_images/')),
                ('heading', models.CharField(blank=True, default='')),
                ('subheading', models.CharField(blank=True, default='')),
                ('paragraph', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
