# Generated by Django 5.2.5 on 2025-08-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0039_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='front',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='front',
            name='logo_image',
        ),
        migrations.RemoveField(
            model_name='front',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='front',
            name='subheading',
        ),
    ]
