# Generated by Django 5.2.5 on 2025-08-21 05:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0040_remove_front_heading_remove_front_logo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
