# Generated by Django 5.2.5 on 2025-08-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0042_alter_galleryphoto_image_alter_item_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image_url',
            new_name='image',
        ),
    ]
