# Generated by Django 5.2.5 on 2025-08-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0044_booking_telegram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking_Telegram',
        ),
    ]
